### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by yurayu1985** [sizifart/SimpleTapBot#3]
2024-08-28 16:39:41.464 | INFO     | __main__:thread:199 - Proccess thread №1 started!
2024-08-28 16:39:42.344 | INFO     | __main__:thread:199 - Proccess thread №2 started!
Exception in thread Thread-1 (thread):
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ShitCoinTapBot\SimpleTapBot-main\SimpleTapBot\main.py", line 204, in thread
    logger.info(f'Thread №{i} | Current balance: {profile_data["data"]["balance"]}')
                                                  ~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'
Exception in thread Thread-2 (thread):
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ShitCoinTapBot\SimpleTapBot-main\SimpleTapBot\main.py", line 204, in thread
    logger.info(f'Thread №{i} | Current balance: {profile_data["data"]["balance"]}')
                                                  ~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'
2024-08-28 16:39:44.133 | INFO     | __main__:thread:199 - Proccess thread №3 started!
Exception in thread Thread-3 (thread):
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ShitCoinTapBot\SimpleTapBot-main\SimpleTapBot\main.py", line 204, in thread
    logger.info(f'Thread №{i} | Current balance: {profile_data["data"]["balance"]}')
                                                  ~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'
Для продолжения нажмите любую клавишу . . .

**Comment by shelllshock** [comment]
Same problem

**Comment by hom9kfun** [comment]
api url was updated just update it
